name: Sync to Official Mirror

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      release_name:
        required: true
        type: string
      release_body:
        required: false
        type: string
    secrets:
      MIRROR_REPO_TOKEN:
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Metadata
        uses: actions/checkout@v4
        with:
          ref: main # Pastikan mengambil versi module.prop terbaru yang baru saja di-push
          fetch-depth: 0

      - name: Sync to Official Repo
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          
          PACKAGE_ID=$(grep "^id=" module.prop | cut -d'=' -f2)
          TARGET_REPO="Xposed-Modules-Repo/$PACKAGE_ID"
          
          git clone https://x-access-token:${{ secrets.MIRROR_REPO_TOKEN }}@github.com/$TARGET_REPO.git mirror
          
          # Mirror tinggal copy module.prop dan README.md dari root private
          cp module.prop README.md mirror/
          
          cd mirror
          git add .
          git commit -m "Release ${{ inputs.tag_name }}" || echo "No changes"
          git push origin main
          
          echo "TARGET_REPO=$TARGET_REPO" >> $GITHUB_ENV

      - name: Fetch APK Artifacts
        run: gh release download ${{ inputs.tag_name }} --pattern "*.apk" --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Mirror Release
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ env.TARGET_REPO }}
          token: ${{ secrets.MIRROR_REPO_TOKEN }}
          files: "*.apk"
          tag_name: ${{ inputs.tag_name }}
          name: ${{ inputs.release_name }}
          draft: false
          prerelease: false
